title: "LF Decentralized Trust Labs"
logo: "lf-decentralized-trust-logo.svg"
url: "https://LF-Decentralized-Trust-labs.github.io"
description: "Start here to propose a LF Decentralized Trust Lab"
show_downloads: "false"
has_children: true
has_toc: true
aux_links:
  "GitHub":
    - "https://github.com/LF-Decentralized-Trust-labs"
  "Chat":
    - "https://discord.lfdecentralizedtrust.org"
theme: just-the-docs
remote_theme: pmarsceill/just-the-docs
plugins:
  - jekyll-remote-theme
repository: LF-Decentralized-Trust-labs/LF-Decentralized-Trust-labs.github.io
